blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('blog/', views.IndexView.as_view(), name='blog'),
    path('blog_list/', views.PostListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', views.PostDetailView.as_view(), name='blog_detail'),
]

webapp/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from top_page.views import index
from kaup_index.views import kaup
from bmi_index.views import bmi
# from blog.views import blog
from valuation.views import valuation
from hinshi_checker.views import hinshi_checker
from .sitemaps import Static_Sitemap

sitemaps = {
    'static': Static_Sitemap(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('kaup/', kaup, name='kaup'),
    path('bmi/', bmi, name='bmi'),
    path('valuation/', valuation, name='valuation'),
    path('blog/', include('blog.urls')),
    path('hinshi-checker', hinshi_checker, name='hinshi_checker'),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='sitemaps'),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Post(models.Model):
    title = models.CharField('タイトル', max_length=200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.title

blog/forms.py
# from django import forms
# from .models import Post

# class PostCreateForm(forms.ModelForm):

#     class Meta:
#         model = Post
#         fields = ('title', 'text')

blog/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from .models import Post
# from .forms import PostCreateForm

# Create your views here.

class IndexView(generic.TemplateView):
    template_name = 'blog/blog.html'

class PostListView(generic.ListView):
    template_name = 'blog/blog_list.html'
    model = Post

class PostDetailView(generic.DetailView):
    template_name = 'blog/blog_detail.html'
    model = Post

# class PostCreateView(generic.CreateView):
#     model = Post
#     form_class = PostCreateForm
#     success_url = reverse_lazy('blog:blog_list')

# def blog(request):
#     return render(request, 'blog/blog.html')

blog/templates/blog/blog.html
{% extends "base.html" %}

{% block extraheader %}
{% load static %}
<title>blog</title>
<meta name="description" content="作成したappのこととか。">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock %}
{% block main %}

<!-- パンくずリスト start -->
<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
    <li itemprop="itemListElement" itemscope
        itemtype="https://schema.org/ListItem">
        <a itemprop="item" href="https://input-and-output.com">
            <span itemprop="name">ホーム</span>
        </a>
        <meta itemprop="position" content="1" />
    </li>
    <li itemprop="itemListElement" itemscope
        itemtype="https://schema.org/ListItem">
        <a itemprop="item" href="https://input-and-output.com/blog/blog/">
            <span itemprop="name">blog</span>
        </a>
        <meta itemprop="position" content="2" />
    </li>
</ol>
<!-- パンくずリスト end -->

作成中


{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}

{% block extraheader %}
{% load static %}
<title>blog</title>
<meta name="description" content="作成したappのこととか。">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock %}

{% block main %}
<!-- パンくずリスト start -->
<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
      <a itemprop="item" href="https://input-and-output.com">
          <span itemprop="name">ホーム</span>
      </a>
      <meta itemprop="position" content="1" />
  </li>
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
      <a itemprop="item" href="https://input-and-output.com/blog/blog_list/">
          <span itemprop="name">blog</span>
      </a>
      <meta itemprop="position" content="2" />
  </li>
  <li itemprop="itemListElement" itemscope
      itemtype="https://schema.org/ListItem">
      <a itemprop="item" href="https://input-and-output.com/blog/blog_detail/{{ post.pk }}/">
          <span itemprop="name">{{ post.title }}</span>
      </a>
      <meta itemprop="position" content="3" />
  </li>
</ol>
<!-- パンくずリスト end -->


<table>
  <tr>
    <th>タイトル</th>
    <td>{{ post.title }}</td>
  </tr>
  <tr>
    <th>本文</th>
    <td>{{ post.text | linebreaksbr}}</td>
  </tr>
  <tr>
    <th>日付</th>
    <td>{{ post.date }}</td>
  </tr>
</table>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends "base.html" %}

{% block extraheader %}
{% load static %}
<title>blog</title>
<meta name="description" content="作成したappのこととか。">
<link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock %}

{% block main %}

<!-- パンくずリスト start -->
<ol class="breadcrumb" itemscope itemtype="https://schema.org/BreadcrumbList">
    <li itemprop="itemListElement" itemscope
        itemtype="https://schema.org/ListItem">
        <a itemprop="item" href="https://input-and-output.com">
            <span itemprop="name">ホーム</span>
        </a>
        <meta itemprop="position" content="1" />
    </li>
    <li itemprop="itemListElement" itemscope
        itemtype="https://schema.org/ListItem">
        <a itemprop="item" href="https://input-and-output.com/blog/blog_list/">
            <span itemprop="name">blog</span>
        </a>
        <meta itemprop="position" content="2" />
    </li>
</ol>
<!-- パンくずリスト end -->

<h1>記事一覧</h1>

<table class="table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
        </tr>
    </thead>
    <tbody>
        {% for blog in post_list %}
        <tr>
            <td><a href="{% url 'blog:blog_detail' blog.pk %}">{{ blog.title }}</a></td>
            <td>{{ blog.date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}