blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # path('blog/', views.IndexView.as_view(), name='blog'),
    path('blog_list/', views.PostListView.as_view(), name='blog_list'),
    path('blog_detail/<int:pk>/', views.PostDetailView.as_view(), name='blog_detail'),
]

webapp/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from top_page.views import index
from kaup_index.views import kaup
from bmi_index.views import bmi
# from blog.views import blog
from valuation.views import valuation
from hinshi_checker.views import hinshi_checker
from .sitemaps import Static_Sitemap

sitemaps = {
    'static': Static_Sitemap(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('kaup/', kaup, name='kaup'),
    path('bmi/', bmi, name='bmi'),
    path('valuation/', valuation, name='valuation'),
    path('blog/', include('blog.urls')),
    path('hinshi-checker', hinshi_checker, name='hinshi_checker'),
    path('sitemap.xml', sitemap, {'sitemaps':sitemaps}, name='sitemaps'),
]

templates/base.html
{% load static %}
{% load django_bootstrap5 %}

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <title>InputAndOutput</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
        {% if GOOGLE_ANALYTICS_TRACKING_ID %}
            {% include 'ga.html' %}
        {% endif %}
        {% block extraheader %}{% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand flex-md-row navbar-dark bg-dark">
            <div class="container justify-content-between">
                <a href="/" class="navbar-brand">input → output</a>
                <ul class="navbar-nav mr-md-2">
                    <li class="nav-item"><a href="{% url 'kaup' %}" class="nav-link">KAUP</a></li>
                    <li class="nav-item"><a href="{% url 'bmi' %}" class="nav-link">BMI</a></li>
                    <li class="nav-item"><a href="{% url 'valuation' %}" class="nav-link">VALUATION</a></li>
                    <li class="nav-item"><a href="{% url 'blog:blog_list' %}" class="nav-link">BLOG</a></li>
                    <li class="nav-item"><a href="/" class="nav-link">hoge</a></li>
                </ul>
            </div>
        </nav>
        <main>
            <div class="container">
                {% block main %}
                {% endblock %}
            </div>
        </main>
    </body>
</html>

templates/ga.html
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-JLWH4G5MM3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-JLWH4G5MM3');
</script>